services:
  - type: web
    name: spacewars-nextjs
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start -- -H 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: HOSTNAME
        value: "0.0.0.0"
    healthCheckPath: /
    domains:
      - spacewars-nextjs.onrender.com
